name: Deploy Static Website to Azure

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'trenor'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AzureAppService_PublishProfile }}
